//@AiCode
namespace SEeAIToDoGenerator.Common.Enums
{
    /// <summary>
    /// Represents the current status of a todo list.
    /// </summary>
    public enum TodoStatus
    {
        /// <summary>
        /// The list is currently being generated by AI.
        /// </summary>
        Generating = 0,

        /// <summary>
        /// The list has been successfully generated and is ready to use.
        /// </summary>
        Ready = 1,

        /// <summary>
        /// An error occurred during list generation.
        /// </summary>
        Error = 2
    }
}
